name: "Licensing"
description: "Questions about license and fair use policies 🎟️"
title: "[LICENSE]: "
labels: question
body:
  - type: checkbox
    id: missing
    attributes:
      label: License missing
      description: Is `LICENSE.yml` not present for this repository?
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Further questions
      description: Any other questions you have 💭
      placeholder: To help maintain the organization repos!
    validations:
      required: false
