name: "Licensing"
description: "Questions about license and fair use policies 🎟️"
title: "[LICENSE]: "
labels: question
body:
  - type: checkboxes
    id: missing
    attributes:
      label: License missing
      description: Is `LICENSE.yml` not present for this repository?
      options:
        - label: Yes, it is missing
          required: true
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Further questions
      description: Any other questions you have 💭
      placeholder: Can I share the project with my friends?
    validations:
      required: false
